name: CI Pipeline - hello-devops

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Récupérer le code source
        uses: actions/checkout@v4

      - name: 2. Configurer l'environnement Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 3. Créer le dossier pour les rapports
        run: mkdir -p reports

      - name: 4. Exécuter les tests unitaires et générer le rapport JUnit
        run: npm test

      - name: 5. Archiver le rapport de test JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml
          retention-days: 7
